# Generated by Django 5.0.6 on 2024-07-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0061_tenant_ai_search_index_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='news_topics',
            field=models.CharField(blank=True, help_text='What kind of news topics would be most helpful', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
