# Generated by Django 5.0.6 on 2024-07-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_tenant_allowed_applications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
    ]
