# Generated by Django 5.0.6 on 2024-07-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_delete_application_delete_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='report_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('question', 'Query'), ('donorReport', 'Donor Story'), ('grantReport', 'Grant Summary'), ('opsReport', 'Ops Insight'), ('impactReport', 'Impact Report')], default='bite', help_text='Data Bite or Data Story', max_length=64),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='html_file_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
