# Generated by Django 5.0.6 on 2024-07-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job Title/Function', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='news_topics',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
