# Generated by Django 5.0.6 on 2024-07-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_job_title_user_news_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='news_topics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_location',
        ),
    ]
